name: dart_crypto
description: Cryptographic for blockchain encryptions & wallets.
version: 1.0.0
homepage: https://steidler.eu

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies:
  base58check: ^2.0.0
  bip39: ^1.0.6
  convert: ^3.0.1
  pointycastle: ^3.1.3
  secp256k1: ^0.3.0
